package net.nani.dairy.sales;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import net.nani.dairy.milk.Shift;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.OffsetDateTime;

@Entity
@Table(name = "delivery_task", indexes = {
        @Index(name = "idx_delivery_task_date", columnList = "task_date"),
        @Index(name = "idx_delivery_task_status", columnList = "status"),
        @Index(name = "idx_delivery_task_customer", columnList = "customer_id"),
        @Index(name = "idx_delivery_task_source_ref", columnList = "source_ref_id")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DeliveryTaskEntity {

    @Id
    @Column(name = "delivery_task_id", length = 80, nullable = false)
    private String deliveryTaskId;

    @Column(name = "task_date", nullable = false)
    private LocalDate taskDate;

    @Column(name = "customer_id", length = 80)
    private String customerId;

    @Column(name = "customer_name", length = 120, nullable = false)
    private String customerName;

    @Column(name = "assigned_to_username", length = 100)
    private String assignedToUsername;

    @Column(name = "assigned_by_username", length = 100)
    private String assignedByUsername;

    @Column(name = "assigned_at")
    private OffsetDateTime assignedAt;

    @Column(name = "route_name", length = 80)
    private String routeName;

    @Enumerated(EnumType.STRING)
    @Column(name = "product_type", length = 30, nullable = false)
    private ProductType productType;

    @Enumerated(EnumType.STRING)
    @Column(name = "task_shift", length = 10)
    private Shift taskShift;

    @Column(name = "preferred_time")
    private LocalTime preferredTime;

    @Column(name = "optimized_stop_order")
    private Integer optimizedStopOrder;

    @Column(name = "planned_eta")
    private LocalTime plannedEta;

    @Column(name = "sla_due_time")
    private LocalTime slaDueTime;

    @Column(name = "sla_breached")
    private Boolean slaBreached;

    @Column(name = "sla_delay_minutes")
    private Integer slaDelayMinutes;

    @Column(name = "optimized_at")
    private OffsetDateTime optimizedAt;

    @Column(name = "planned_qty_liters", nullable = false)
    private double plannedQtyLiters;

    @Column(name = "unit_price", nullable = false)
    private double unitPrice;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_mode", length = 30, nullable = false)
    private PaymentMode paymentMode;

    @Column(name = "delivered_qty_liters")
    private Double deliveredQtyLiters;

    @Column(name = "sale_id", length = 80)
    private String saleId;

    @Column(name = "sale_recorded_at")
    private OffsetDateTime saleRecordedAt;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 20, nullable = false)
    private DeliveryTaskStatus status;

    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated;

    @Column(name = "source_ref_id", length = 140, unique = true)
    private String sourceRefId;

    @Column(name = "notes", length = 500)
    private String notes;

    @Column(name = "created_by", length = 100)
    private String createdBy;

    @Column(name = "completed_by", length = 100)
    private String completedBy;

    @Column(name = "completed_at")
    private OffsetDateTime completedAt;

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    @PrePersist
    public void prePersist() {
        OffsetDateTime now = OffsetDateTime.now();
        createdAt = now;
        updatedAt = now;
        if (status == null) status = DeliveryTaskStatus.PENDING;
        if (paymentMode == null) paymentMode = PaymentMode.CREDIT;
        if (taskShift == null) taskShift = Shift.AM;
        if (productType == null) productType = ProductType.MILK;
    }

    @PreUpdate
    public void preUpdate() {
        updatedAt = OffsetDateTime.now();
    }
}
