package net.nani.dairy.sales.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import net.nani.dairy.milk.Shift;
import net.nani.dairy.sales.DeliveryTaskStatus;
import net.nani.dairy.sales.PaymentMode;
import net.nani.dairy.sales.ProductType;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.OffsetDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DeliveryTaskResponse {
    private String deliveryTaskId;
    private LocalDate taskDate;
    private String customerId;
    private String customerName;
    private String assignedToUsername;
    private String assignedByUsername;
    private OffsetDateTime assignedAt;
    private String routeName;
    private ProductType productType;
    private Shift taskShift;
    private LocalTime preferredTime;
    private double plannedQtyLiters;
    private double unitPrice;
    private PaymentMode paymentMode;
    private Double deliveredQtyLiters;
    private DeliveryTaskStatus status;
    private boolean autoGenerated;
    private String sourceRefId;
    private String saleId;
    private OffsetDateTime saleRecordedAt;
    private String notes;
    private String createdBy;
    private String completedBy;
    private OffsetDateTime completedAt;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
}
